### ISSUE TITLE
`lsb-dist': 不是有效的标识符

### ISSUE THREAD

**Issue by iamdanielyin** [feiskyer/ops#1]
sh kubernetes/install-docker.sh 
kubernetes/lib/util.sh:行26: `lsb-dist': 不是有效的标识符

sh kubernetes/install-kubernetes.sh
kubernetes/lib/util.sh:行26: `lsb-dist': 不是有效的标识符

**Comment by feiskyer** [comment]
@yinfxs try `bash kubernetes/install-docker.sh`
